[[Tandem]]
arch = "aarch64"
git-tree-sha1 = "57f0d4f36ba02340af3b1816a214b317f23b19ee"
mpi = "mpich"
os = "macos"

    [[Tandem.download]]
    sha256 = "07345919bab341c46e8b5f19b4b3bbf8d1084e86498834de315562a02bf28433"
    url = "https://github.com/boriskaus/Tandem_jll.jl/releases/download/Tandem-v1.2.0+0/Tandem.v1.2.0.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[Tandem]]
arch = "x86_64"
git-tree-sha1 = "7e59b61a2dcd41d4de013f8ea521d0aac13a9810"
mpi = "mpich"
os = "macos"

    [[Tandem.download]]
    sha256 = "f6c287dbb761a64ac515998442b18f19092b290e66f553e0a9301f83d41fc823"
    url = "https://github.com/boriskaus/Tandem_jll.jl/releases/download/Tandem-v1.2.0+0/Tandem.v1.2.0.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[Tandem]]
arch = "x86_64"
git-tree-sha1 = "cc132b6f1143fa269415c88961c22d519ffb4a1f"
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[Tandem.download]]
    sha256 = "6ae6b5f1dcc5a2c9216936c195a6ecf23e095289c29ffeeaf4e52d88f9a6c5b8"
    url = "https://github.com/boriskaus/Tandem_jll.jl/releases/download/Tandem-v1.2.0+0/Tandem.v1.2.0.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[Tandem]]
arch = "x86_64"
git-tree-sha1 = "0309900fb0ad0eb1120354908393ebddbf5923f8"
mpi = "microsoftmpi"
os = "windows"

    [[Tandem.download]]
    sha256 = "3a99c2bb3cd9db13413fcad8e6f633639ff1a7d3d8288aaf3a97869b612289f6"
    url = "https://github.com/boriskaus/Tandem_jll.jl/releases/download/Tandem-v1.2.0+0/Tandem.v1.2.0.x86_64-w64-mingw32-mpi+microsoftmpi.tar.gz"
