# Autogenerated wrapper script for tandem_jll for aarch64-apple-darwin-mpi+mpich
export static_2d_p1, static_2d_p2, static_2d_p3, static_3d_p1, static_3d_p2, static_3d_p3, tandem_2d_p1, tandem_2d_p2, tandem_2d_p3, tandem_3d_p1, tandem_3d_p2, tandem_3d_p3

using PETSc_jll
using PARMETIS_jll
using METIS_jll
using HDF5_jll
using Lua_jll
using Zlib_jll
using libblastrampoline_jll
using LLVMOpenMP_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("tandem")
JLLWrappers.@declare_executable_product(static_2d_p1)
JLLWrappers.@declare_executable_product(static_2d_p2)
JLLWrappers.@declare_executable_product(static_2d_p3)
JLLWrappers.@declare_executable_product(static_3d_p1)
JLLWrappers.@declare_executable_product(static_3d_p2)
JLLWrappers.@declare_executable_product(static_3d_p3)
JLLWrappers.@declare_executable_product(tandem_2d_p1)
JLLWrappers.@declare_executable_product(tandem_2d_p2)
JLLWrappers.@declare_executable_product(tandem_2d_p3)
JLLWrappers.@declare_executable_product(tandem_3d_p1)
JLLWrappers.@declare_executable_product(tandem_3d_p2)
JLLWrappers.@declare_executable_product(tandem_3d_p3)
function __init__()
    JLLWrappers.@generate_init_header(PETSc_jll, PARMETIS_jll, METIS_jll, HDF5_jll, Lua_jll, Zlib_jll, libblastrampoline_jll, LLVMOpenMP_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_executable_product(
        static_2d_p1,
        "bin/static_2d_p1",
    )

    JLLWrappers.@init_executable_product(
        static_2d_p2,
        "bin/static_2d_p2",
    )

    JLLWrappers.@init_executable_product(
        static_2d_p3,
        "bin/static_2d_p3",
    )

    JLLWrappers.@init_executable_product(
        static_3d_p1,
        "bin/static_3d_p1",
    )

    JLLWrappers.@init_executable_product(
        static_3d_p2,
        "bin/static_3d_p2",
    )

    JLLWrappers.@init_executable_product(
        static_3d_p3,
        "bin/static_3d_p3",
    )

    JLLWrappers.@init_executable_product(
        tandem_2d_p1,
        "bin/tandem_2d_p1",
    )

    JLLWrappers.@init_executable_product(
        tandem_2d_p2,
        "bin/tandem_2d_p2",
    )

    JLLWrappers.@init_executable_product(
        tandem_2d_p3,
        "bin/tandem_2d_p3",
    )

    JLLWrappers.@init_executable_product(
        tandem_3d_p1,
        "bin/tandem_3d_p1",
    )

    JLLWrappers.@init_executable_product(
        tandem_3d_p2,
        "bin/tandem_3d_p2",
    )

    JLLWrappers.@init_executable_product(
        tandem_3d_p3,
        "bin/tandem_3d_p3",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
